FUSEX: Drop user-provided copy constructor
In file included from fusex/eosxd/eosfuse.hh:34,
                 from fusex/kv/NoKV.cc:26:
fusex/md/md.hh: In constructor ‘metad::flushentry::flushentry(uint64_t,
  const std::string&, metad::mdx::md_op, fuse_req_t)’:
fusex/md/md.hh:872:31:
 error: implicitly-declared ‘fuse_id& fuse_id::operator=(const fuse_id&)’
 is deprecated [-Werror=deprecated-copy]
  872 |         _fuse_id = fuse_id(req);
      |                               ^
In file included from fusex/backend/backend.hh:30,
                 from fusex/md/md.hh:33:
fusex/misc/FuseId.hh:66:3: note: because ‘fuse_id’ has user-provided
  ‘fuse_id::fuse_id(const fuse_id&)’
   66 |   fuse_id(const fuse_id& o)
      |   ^~~~~~~