COMMON: Use aggregate initialization for struct timespec
Fixes the warning below by initializing both members of the timespec
struct.

common/PthreadRWMutex.cc: In member function
  ‘virtual int eos::common::PthreadRWMutex::TimedWrLock(uint64_t)’:
common/PthreadRWMutex.cc:142:31: error: missing initializer for member
  ‘timespec::tv_nsec’ [-Werror=missing-field-initializers]
  142 |   struct timespec timeout = {0};
      |                               ^